### ISSUE TITLE
only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT

### ISSUE THREAD

**Issue by jmoral** [rediris-es/simplesamlphp-module-oidc#10]
Following installation instructions, I get this error after clicking in "instalar" button:
```SimpleSAML_Error_Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:45 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Database error: SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
Backtrace:
7 lib/SimpleSAML/Database.php:221 (SimpleSAML\Database::query)
6 lib/SimpleSAML/Database.php:262 (SimpleSAML\Database::write)
5 modules/oidc/lib/Services/DatabaseMigration.php:92 (SimpleSAML\Modules\OpenIDConnect\Services\DatabaseMigration::version20180305180300)
4 modules/oidc/lib/Services/DatabaseMigration.php:68 (SimpleSAML\Modules\OpenIDConnect\Services\DatabaseMigration::migrate)
3 modules/oidc/lib/Controller/OpenIdConnectInstallerController.php:67 (SimpleSAML\Modules\OpenIDConnect\Controller\OpenIdConnectInstallerController::__invoke)
2 modules/oidc/lib/Services/RoutingService.php:44 (SimpleSAML\Modules\OpenIDConnect\Services\RoutingService::call)
1 modules/oidc/www/install.php:18 (require)
0 www/module.php:135 (N/A)
```

Environment
- centos 7 
- mariadb-5.5.56-2.el7.x86_64
- simplesamlphp 1.15.4

**Comment by tvdijen** [comment]
I think this relates to https://github.com/simplesamlphp/simplesamlphp/issues/504
Have you tried using SSP 1.16 beta?

**Comment by jmoral** [comment]
I think this issue is not related to consent module.

If I remove one CURRENT_TIMESTAMP from this file https://github.com/rediris-es/simplesamlphp-module-oidc/blob/master/lib/Services/DatabaseMigration.php, this module is installed.

**Comment by sgomez** [comment]
I tried to be compatible with (almost) any DBMS using ANSI SQL and the module was tested with last versions of mariadb, mysql, postgresql and sqlite. 

CURRENT_TIMESTAMP was added for this reason in 3166d97f96dfedf4a8fd2c51e968671a4d5b3444 commit. Previously I had a default value but we had problems with others DBMS (cc @lonoak).

I guess the problem here is that mariadb 5.5 has the same limitation than [5.5 mysql versions](https://stackoverflow.com/questions/4489548/why-there-can-be-only-one-timestamp-column-with-current-timestamp-in-default-cla). This issue was resolved in mysql >= 5.6 and mariadb >= 10.

I'm going to talk with @lonoak about this.

**Comment by sgomez** [comment]
@jmoral can you update to MariaDB 10.x? This could resolve the issue and I could add this as a requirement in the README.

It is too hard to be compatible with any DBMS and the problem with "only one CURRENT_TIMESTAMP"  is an issue of MySql5/MariaDB 5.5.

MySql5.5 is out of maintenance and MariaDB 5.5 will be maintained until Apr, 2020.

**Comment by lonoak** [comment]
A side comment... I prefer using the [IUS repository](https://ius.io/) for a number of reasons... indeed, they have [MariaDB 10.1.32 available](https://redir.is/UF4GY) for CentOS 7.

**Comment by jmoral** [comment]
db created successfully using mariadb100u-server. 
Thanks
